from pyspark.sql.types import *

case_schema = StructType([
    StructField("ticketId", StringType(), True),
    StructField("createDate", StringType(), True),
    StructField("problemSummary", StringType(), True),
    StructField("status", StringType(), True),
    StructField("ttrStop", TimestampType(), True),
    StructField("accountNumber", StringType(), True),
    StructField("lob", StringType(), True),
    StructField("problemTypeId", StringType(), True),
    StructField("queueName", StringType(), True),
    StructField("solutionDesc", StringType(), True),
    StructField("customerOutcome", StringType(), True),
    StructField("nickname", StringType(), True),
    StructField("customerVisible", BooleanType(), True),
    StructField("isCancelled", BooleanType(), True),
    StructField("cancelReason", StringType(), True),
    StructField("closedDate", StringType(), True),
    StructField("previousState", StringType(), True),
    StructField("problemType", StringType(), True),
    StructField("additionalProblemDetails", StringType(), True),
    StructField("resolutionDetails", StringType(), True),
    StructField("additionalResolutionDetails", StringType(), True),
    StructField("problemDetails", StringType(), True),
    StructField("shortDescription", StringType(), True),
    StructField("updateDate", StringType(), True),
    StructField("assigned_to", StringType(), True),
    StructField("submitter", StringType(), True),
    StructField("frt", TimestampType(), True),
    StructField("isCommercial", BooleanType(), True),
    StructField("userRetention", BooleanType(), True),
    StructField("userManagement", BooleanType(), True),
    StructField("userExecutive", BooleanType(), True),
]
)